
export const COLORS = {
  primaryDark: '#2C4A24',
  primary: '#4F6E43',
  deepAccent: '#344E41',
  gold: '#D1A980',
  background: '#F5EEE0',
};

export const LOGO_URL = 'https://i.postimg.cc/Xp7TbQzD/a9497882-50c5-4d02-a197-aa8945ebea5f.png';

export const TRANSLATIONS = {
  ar: {
    appName: 'مِحكاة',
    slogan: 'رفيقك في رحلة الحريق الزراعية',
    tagline: 'المزرعة التي تحكي قصتك وتخلّد ذكرياتك',
    start: 'ابدأ جولتك الآن',
    step1: 'صوّر شجرة أمامك',
    step2: 'اكتشف حكايتها السرية',
    step3: 'وثّق أثرك في المزرعة',
    visitorName: 'ما هو اسمك أيها الرحالة؟',
    visitorType: 'أهلاً بك، من معنا اليوم؟',
    typeChild: 'برعم صغير (طفل)',
    typeFamily: 'عائلة محبة',
    typeTourist: 'سائح مستكشف',
    next: 'انطلق',
    uploadTitle: 'صوّر كنوز الطبيعة',
    uploadHint: 'وجّه الكاميرا نحو النبتة أو الشجرة التي لفتت نظرك في المزرعة',
    createStory: 'استنطق الشجرة',
    savePlant: 'سجّل هذه الذكرى باسمي',
    library: 'سجل زياراتي',
    myPlants: 'نباتاتي المكتشفة',
    details: 'تفاصيل الحكاية',
    statusSeed: 'بذرة ذكرى',
    statusGrow: 'تنمو في ذاكرتي',
    statusBloom: 'تزهر بالجمال',
    statusFruit: 'أثمرت بالمعرفة',
    updateStatus: 'تحديث حالة اكتشافي',
    back: 'العودة للمزرعة',
    loading: 'جاري استحضار روح الأرض وحكايا الحريق...',
    noPlants: 'لم تبدأ بجمع حكاياك بعد. المزرعة بانتظارك!',
    history: 'تاريخ الاكتشاف',
  },
  en: {
    appName: 'Mahkāh',
    slogan: 'Your Al-Hariq Agri-Tour Companion',
    tagline: 'The farm that tells your story and preserves your legacy',
    start: 'Start Your Tour',
    step1: 'Snap a tree in front of you',
    step2: 'Discover its secret tale',
    step3: 'Document your farm footprint',
    visitorName: 'What is your name, explorer?',
    visitorType: 'Welcome! Who is with us today?',
    typeChild: 'Little Sprout (Child)',
    typeFamily: 'Loving Family',
    typeTourist: 'Agri-Tourist',
    next: 'Let\'s Go',
    uploadTitle: 'Snap Nature\'s Treasure',
    uploadHint: 'Point your camera at a plant or tree you found in the farm',
    createStory: 'Unveil the Story',
    savePlant: 'Save This Memory',
    library: 'My Tour Log',
    myPlants: 'Discovered Plants',
    details: 'The Tale\'s Details',
    statusSeed: 'Memory Seed',
    statusGrow: 'Growing in Memory',
    statusBloom: 'Blooming with Beauty',
    statusFruit: 'Fruition of Knowledge',
    updateStatus: 'Update Discovery Status',
    back: 'Back to Farm',
    loading: 'Evoking the soul of the land and Al-Hariq tales...',
    noPlants: 'No stories collected yet. The farm is waiting!',
    history: 'Discovery Date',
  }
};
